BBBB BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Sign Up - Repoetry') XXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        XX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        XXXXX X
            XXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXX XXX XX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
        X
        X X
            XXXXXXXXXXX XXXXX
        X
        X X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
        X
        XXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X
        XXXXXXXX X
            XXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Create Your Repoetry Account') XXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Choose a Username') X XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter Password') X XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Confirm Password') X XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXX gettext(u'Sign Up') XXXXXXXXX
        XXXXXXX

        XXX gettext(u'Already have an account?')  XX XXXXXXBBB BBBBBBBXX gettext(u'Login') XXXXXXXX

        BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
                BB BBBBBBBBBB BB BBBBBBBBBBBBB BB BBBBBBBBBB BB BBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            BBBBBB
        BBBBB

        XXXX X XXXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXXXX XXXXXXXXXXXXXXX gettext(u'Select Language:') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX
